# Inputs
Get the files located here :

```
/eos/home-v/vovechki/MonoJetOut
```

```
scp -r vovechki@lxplus.cern.ch:/eos/home-v/vovechki/MonoJetOut .
```

# Some Modifications

[1] go into the directory and change the directory naming


In [1]:
!cd MonoJetOut && mv xml config

[2] Change a single line in the top level config file
```
MonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml
```
Do not run the following command if you did not scp a new version of MonoJetOut

In [2]:
!sed '14d' MonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml > temp.xml 

But be careful, this command above is a hack and "irreversibly modifies" the xml config file.  If you run it twice, then it will crash everything when you try to run the xml2json command below. 

In [3]:
!cp temp.xml MonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml

# pyhf Stuff

Start by importing the necessary tools

In [1]:
import logging
import json
import pyhf
from pyhf import Model,Workspace

Convert the xml workspace from Giuliano to a pyhf compatible JSON spec

In [2]:
!ls `pwd`MonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml

ls: /Users/vlad/Documents/EPEprojects/MonoJetPresMonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml: No such file or directory


In [4]:
!pyhf xml2json --hide-progress `pwd`/MonoJetOut/config/ShapeFit_std_CRFit_3kfactors_XXXX/BkgOnly_L138p97ifb.xml --basedir `pwd`/MonoJetOut | tee monojet.json

{
    "channels": [
        {
            "name": "SR_200_cuts",
            "samples": [
                {
                    "data": [
                        22117.69921875
                    ],
                    "modifiers": [
                        {
                            "data": [
                                148.72019958496094
                            ],
                            "name": "staterror_SR_200_cuts",
                            "type": "staterror"
                        },
                        {
                            "data": {
                                "hi": 2.0,
                                "lo": 0.001
                            },
                            "name": "multijet_NCB_Sys",
                            "type": "normsys"
                        }
                    ],
                    "name": "multijet_NCB_200"
                },
                {
                    "data": [
                        860285.25
  

                            ],
                            "name": "staterror_SR_200_cuts",
                            "type": "staterror"
                        },
                        {
                            "data": {
                                "hi": 1.017,
                                "lo": 0.983
                            },
                            "name": "lumiSys",
                            "type": "normsys"
                        }
                    ],
                    "name": "ZtautauVBF_200"
                },
                {
                    "data": [
                        9160.025390625
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "lumi",
                            "type": "lumi"
                        },
                        {
                            "data": [
                                35.7835115021
      

                            },
                            "name": "MUON_EFF_RECO_STAT",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 0.99433,
                                "lo": 1.00562
                            },
                            "name": "MUON_EFF_RECO_SYS",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 0.99689,
                                "lo": 1.00311
                            },
                            "name": "MUON_EFF_RECO_SYS_LOWPT",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 0.99863,
                                "lo": 1.00152
                            },
        

                            "data": {
                                "hi": 0.99967,
                                "lo": 1.00861
                            },
                            "name": "JET_JER_EffectiveNP_2",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 1.00084,
                                "lo": 1.00564
                            },
                            "name": "JET_JER_EffectiveNP_3",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 1.00053,
                                "lo": 1.0032
                            },
                            "name": "JET_JER_EffectiveNP_4",
                            "type": "normsys"
                        },
                        {
                            "data":

                        },
                        {
                            "data": {
                                "hi": 1.004,
                                "lo": 1.00008
                            },
                            "name": "JET_JER_EffectiveNP_10",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 1.00011,
                                "lo": 1.00157
                            },
                            "name": "JET_JER_EffectiveNP_11",
                            "type": "normsys"
                        },
                        {
                            "data": {
                                "hi": 1.00234,
                                "lo": 0.99766
                            },
                            "name": "JET_JER_EffectiveNP_12restTerm",
                            "type": "normsys"
                        }

                        {
                            "data": [
                                0.0242066236219
                            ],
                            "name": "staterror_CR1e0b_350_cuts",
                            "type": "staterror"
                        }
                    ],
                    "name": "ZeeVBF_350"
                },
                {
                    "data": [
                        1.8148518800735474
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "lumi",
                            "type": "lumi"
                        },
                        {
                            "data": [
                                0.344752188603
                            ],
                            "name": "staterror_CR1e0b_350_cuts",
                            "type": "staterror"
                        },
                      

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Validate that the spec you just created is valid

In [5]:
import json, requests, jsonschema
workspace = json.load(open('monojet.json'))

# This line breaks so I just got the schema from the url
# schema = requests.get('https://diana-hep.org/pyhf/schemas/1.0.0/workspace.json').json()
schema = {
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "https://scikit-hep.org/pyhf/schemas/1.0.0/workspace.json",
    "$ref": "defs.json#/definitions/workspace"
}

jsonschema.validate(instance=workspace, schema=schema)

Or by using the stuff from pyhf (because Giordon says its better in a magic way)

In [6]:
pyhf.utils.validate(workspace, 'workspace.json')

Now we need to create a "patch" because the POI for the measurement that we will perform in ouir workspace is called "mu_SIG" but this is actually not used in the bkg-only fit, so we need to remove it from the model.:
- https://python-json-patch.readthedocs.io/en/latest/tutorial.html
- http://jsonpatch.com/    

You could go and modify the initial XML file to replace "mu_SIG" by "lumi" but that is a bick of a hack.

In [7]:
import jsonpatch
patch = jsonpatch.JsonPatch([{'op': 'replace', 'path': '/measurements/0/config/poi', 'value': 'lumi'}])

Does this patch do what we think it should do?

In [8]:
sam = { "measurements": [{"config":{"poi":"CHANGETHIS"}}, {"this":2}] }
print(sam)

{'measurements': [{'config': {'poi': 'CHANGETHIS'}}, {'this': 2}]}


In [9]:
patch.apply(sam)

{'measurements': [{'config': {'poi': 'lumi'}}, {'this': 2}]}

Yeah, that looks like it replaced the thing that we wanted to change.

In [10]:
ws = pyhf.Workspace(patch.apply(workspace))

In [11]:
ws.spec

AttributeError: 'Workspace' object has no attribute 'spec'

Now extract the model from the workspace

In [13]:
m = ws.model()

Print the "data" associated with the model.  Note that the "data" here has two components :
- The observed event counts in a given bin
- The NP's that will eventually be constrained.  These are referred to as "data" in the pyhf and HF lingo because they are indeed measurements that come from the data (e.g. luminosity, JES).

This is a bit of a subtle point and confusing but essential to allow us to get at the technical bits and pieces we are interested in examining.

In [14]:
d = ws.data(m)
print(d)

[19.0, 13.0, 10.0, 106425.0, 29551.0, 13592.0, 9749.0, 2596.0, 767.0, 305.0, 107.0, 51.0, 234.0, 121.0, 125.0, 338998.0, 174890.0, 86339.0, 43781.0, 36025.0, 11695.0, 4392.0, 1868.0, 817.0, 389.0, 32.0, 21.0, 22.0, 71075.0, 36162.0, 17973.0, 9065.0, 7278.0, 2476.0, 834.0, 357.0, 155.0, 81.0, 23.0, 9.0, 18.0, 105155.0, 47931.0, 21794.0, 10390.0, 7822.0, 2388.0, 774.0, 306.0, 129.0, 61.0, 413.0, 187.0, 207.0, 1791624.0, 752328.0, 313912.0, 141036.0, 102888.0, 29458.0, 10203.0, 3986.0, 1663.0, 738.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.

Display the initial values of the nuissance parameters in our model.

In [15]:
m.config.suggested_init()

[1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

Evaluate the value of the likelihood of the model and the data at the value of the NP's that are their initial starting values.

In [16]:
m.logpdf(m.config.suggested_init(), d)

array([-32382.79741221])

You can toggle the available backends here, which is the machinery that will be used to perform the likelihood minimization.

This call will let you know what backends you have at your disposal, and then you can perform the minimization below by choosing from among the entries in this list.

In [25]:
pyhf.get_backend()

(<pyhf.tensor.numpy_backend.numpy_backend at 0x104b017d0>,
 <pyhf.optimize.opt_scipy.scipy_optimizer at 0x104b01e90>)

We will choose the second one, which on Sam's machine is scipy_optimizer

In [18]:
opt = pyhf.get_backend()[1]

Using this optimizer we will now perform the unconstrained fit, meaning that all NP's and the POI are free to be pulled.

This will return the values of the NP's that minimize the likelihood

In [21]:
# If get missing attribute error from code cell below
pyhf.set_backend("numpy")
bfit = pyhf.infer.mle.fit(d, m)

In [19]:
bfit = opt.unconstrained_bestfit(pyhf.utils.loglambdav, d, m, m.config.suggested_init(), m.config.suggested_bounds() )

AttributeError: 'scipy_optimizer' object has no attribute 'unconstrained_bestfit'

We can now print the values of those NP's.  Note that since the input data is the asimov dataset, they are very close to the input values

In [22]:
bfit

array([ 1.08993126e+00, -2.97791095e-03,  1.00000702e+00, -1.97245615e-03,
       -1.96338307e-03,  1.97528075e-03,  2.06593824e-02, -1.99385673e-03,
       -1.96907541e-03,  1.97304799e-03,  5.59700229e-03,  9.61578260e-02,
       -1.45563099e-01,  1.97048486e-03, -1.97676384e-03, -1.97528564e-03,
       -1.97103195e-03,  3.92040412e-02, -1.97618897e-03, -2.00625554e-03,
        2.00084396e-03, -1.98118512e-03, -1.99198737e-03,  9.61744190e-02,
        9.61419645e-02, -1.97344503e-03, -9.61734984e-02,  2.19448610e-01,
        1.07033924e-01,  9.61551782e-02, -1.07844272e-01,  9.61506588e-02,
        9.61686679e-02,  2.47741521e-02, -1.97305182e-03,  2.63874474e-02,
       -1.98189165e-03, -1.97278804e-03, -1.98716951e-03,  4.51549017e-02,
        1.99969564e-03,  1.99752973e-03,  2.00359040e-03,  2.02330960e-02,
       -1.99272841e-03,  9.61465793e-02,  9.61509716e-02,  2.03448574e-03,
        9.61428508e-02,  9.61447731e-02,  9.61642837e-02,  9.61491792e-02,
        1.07092272e+00, -

And you can show the "actual" data which is the event counts that we are fitting out model to.

In [23]:
m.expected_actualdata(bfit)

array([2.21071959e+01, 1.21724014e+01, 1.15761750e+01, 1.12248495e+05,
       3.26046022e+04, 1.59205185e+04, 1.14679868e+04, 3.13220848e+03,
       9.64131512e+02, 3.58688726e+02, 1.23436071e+02, 5.95415932e+01,
       2.06291678e+02, 1.06168535e+02, 1.27327565e+02, 3.39815481e+05,
       1.76553407e+05, 8.71920214e+04, 4.42201493e+04, 3.62138877e+04,
       1.20384024e+04, 4.47899582e+03, 1.89983011e+03, 8.61319827e+02,
       4.10754576e+02, 3.82706257e+01, 1.84144684e+01, 1.98908039e+01,
       7.03041460e+04, 3.58889915e+04, 1.75528265e+04, 8.87478725e+03,
       7.33749042e+03, 2.40378537e+03, 8.95432775e+02, 3.63576560e+02,
       1.61202518e+02, 7.77531614e+01, 2.87414176e+01, 1.51534351e+01,
       1.55720847e+01, 1.06012904e+05, 4.84910649e+04, 2.18388408e+04,
       1.04201322e+04, 7.83128257e+03, 2.34459316e+03, 8.10480803e+02,
       3.13244858e+02, 1.29760206e+02, 5.81322183e+01, 3.56474540e+02,
       1.80672904e+02, 2.15223427e+02, 1.83168793e+06, 7.67846957e+05,
      

... or we can look at the full "data" list, which as we recall is both the event counts and the nuissance parameters which come into the constraint terms in the likelihood.

In [24]:
m.expected_data(bfit)

array([ 2.21071959e+01,  1.21724014e+01,  1.15761750e+01,  1.12248495e+05,
        3.26046022e+04,  1.59205185e+04,  1.14679868e+04,  3.13220848e+03,
        9.64131512e+02,  3.58688726e+02,  1.23436071e+02,  5.95415932e+01,
        2.06291678e+02,  1.06168535e+02,  1.27327565e+02,  3.39815481e+05,
        1.76553407e+05,  8.71920214e+04,  4.42201493e+04,  3.62138877e+04,
        1.20384024e+04,  4.47899582e+03,  1.89983011e+03,  8.61319827e+02,
        4.10754576e+02,  3.82706257e+01,  1.84144684e+01,  1.98908039e+01,
        7.03041460e+04,  3.58889915e+04,  1.75528265e+04,  8.87478725e+03,
        7.33749042e+03,  2.40378537e+03,  8.95432775e+02,  3.63576560e+02,
        1.61202518e+02,  7.77531614e+01,  2.87414176e+01,  1.51534351e+01,
        1.55720847e+01,  1.06012904e+05,  4.84910649e+04,  2.18388408e+04,
        1.04201322e+04,  7.83128257e+03,  2.34459316e+03,  8.10480803e+02,
        3.13244858e+02,  1.29760206e+02,  5.81322183e+01,  3.56474540e+02,
        1.80672904e+02,  

Finally, we can take the difference between the fitted NPs and the initial values that we started with and that gives us the pull of that NP.

In [25]:
bfit-m.config.suggested_init()

array([ 8.99312563e-02, -2.97791095e-03,  7.01520274e-06, -1.97245615e-03,
       -1.96338307e-03,  1.97528075e-03,  2.06593824e-02, -1.99385673e-03,
       -1.96907541e-03,  1.97304799e-03,  5.59700229e-03,  9.61578260e-02,
       -1.45563099e-01,  1.97048486e-03, -1.97676384e-03, -1.97528564e-03,
       -1.97103195e-03,  3.92040412e-02, -1.97618897e-03, -2.00625554e-03,
        2.00084396e-03, -1.98118512e-03, -1.99198737e-03,  9.61744190e-02,
        9.61419645e-02, -1.97344503e-03, -9.61734984e-02,  2.19448610e-01,
        1.07033924e-01,  9.61551782e-02, -1.07844272e-01,  9.61506588e-02,
        9.61686679e-02,  2.47741521e-02, -1.97305182e-03,  2.63874474e-02,
       -1.98189165e-03, -1.97278804e-03, -1.98716951e-03,  4.51549017e-02,
        1.99969564e-03,  1.99752973e-03,  2.00359040e-03,  2.02330960e-02,
       -1.99272841e-03,  9.61465793e-02,  9.61509716e-02,  2.03448574e-03,
        9.61428508e-02,  9.61447731e-02,  9.61642837e-02,  9.61491792e-02,
        7.09227209e-02, -

# Open Point
The open, and important point, is that the manner in which the error on a given NP is not well defined here in pyhf it seems.